### ISSUE TITLE
请问如何对表格做重新的初始化请求

### ISSUE THREAD

**Issue by caojinjie** [ahooksjs/useTable#14]
场景说明：表格页面有如下布局，左侧为类型导航，右侧为表格（使用useNextFormTable
实现），表格依赖左侧选中的导航类型；表格内部操作（如搜索、排序、分页等）均可使用useNextFormTable API实现，当切换左侧类型导航时，需要重置表格所有参数并根据类型重新请求；

**Comment by caojinjie** [comment]
补充说明：在https://github.com/ahooksjs/useTable/issues/12 问题中，也涉及到当前问题的场景，即右侧表格是前端过滤的场景，切换左侧类型时，需要触发表格的整体数据重新加载；

**Comment by monkindey** [comment]
https://github.com/ahooksjs/useTable/releases/tag/v0.2.0 已经解决
