### ISSUE TITLE
请问如何能操作表格已生效过滤条件状态？

### ISSUE THREAD

**Issue by caojinjie** [ahooksjs/useTable#15]
场景说明：

使用useNextFormTable和useFilterPlugin实现表格过滤，
如过滤项为类型列，由于类型列完整过滤候选项过多，期望该列候选项只是列表数据中已有数据的类型集合，
eg：比如完整类型为[1,2,3,4,5,6,7,8,9]，表格数据有80条，这80条对应的类型只存在了[1,2,3,4]，那么类型列候选项则只有[1,2,3,4]，而不是[1,2,3,4,5,6,7,8,9]

当出现如下情况时，需要手动操作过滤状态
eg：上述80条数据我选择了类型按照[1,2]过滤，此时表格受多用户操作影响，类型为2的数据被其他用户删除掉了，那么此时过滤候选项应该去除2，并且已生效的过滤条件也去除2
此时我需要做状态控制，请问这种情况我是否应当在middlewares中操作状态，如何改写状态尚未找到方式。

**Comment by monkindey** [comment]
感觉这个需求不太合理，如果这种合理的话，那么 form 的查询条件也要跟着 table 数据的删除而变？

**Comment by caojinjie** [comment]
经过一番游说，哔掉了这个需求 - -。
