### ISSUE TITLE
使用useSortablePlugin时，只设置defaultValue时报错

### ISSUE THREAD

**Issue by caojinjie** [ahooksjs/useTable#17]
useSortablePlugin API中参数均是可选，当只设置defaultValue时（如：useSortablePlugin({defaultValue:{email:'asc'}})）页面报错，多添加一个配置{resetWhenQuery:false}时，页面可以正确渲染

**Comment by caojinjie** [comment]
复现Demo可参数官方Demo基本展示（https://usetable-ahooks.js.org/hooks/plugin/use-sortable-plugin#%E5%9F%BA%E6%9C%AC%E4%BD%BF%E7%94%A8），在codesandbox中编辑添加useSortablePlugin({defaultValue:{email:'asc'}})）即可。

**Comment by monkindey** [comment]
无复现
