### ISSUE TITLE
useFormTable中期望onFilter回调中能支持传空对象，以便于清空所有过滤项

### ISSUE THREAD

**Issue by caojinjie** [ahooksjs/useTable#19]
**场景描述：**

页面基于useFormTable开发，这边有一需求是在表格上方添加了“清除过滤”按钮，点击时清除表格所有过滤项，即表格所有列头的过滤项清除；

**实现方式：**

在按钮的onClick事件中调用ahooks返回的tableProps.onFilter事件，传参为{}；

**期望效果：**

进入service时，过滤条件为空；

**实际效果：**

进入service时，过滤条件依然还有；

**Comment by monkindey** [comment]
Closed by https://github.com/ahooksjs/useTable/commit/852ee6a780a508bd9d40e3edc2c5dbd56fe72f20
