### ISSUE TITLE
表单查询之后，query 方法 current 无法记录分页信息

### ISSUE THREAD

**Issue by Z8264** [ahooksjs/useTable#29]
点击表单查询之后
选择第3页，再次调用query方法，会被重置到第1页，无法记录分页状态。

**Comment by monkindey** [comment]
有没有复现的 demo 呢？

**Comment by Z8264** [comment]
@monkindey
https://usetable-ahooks.js.org/hooks/next/next-form-table
![image](https://user-images.githubusercontent.com/7948534/143211288-d673e8d5-c9ea-4f76-b410-41280513ca4a.png)
官方的demo就可以，
先点击查询按钮，再点击第三页，然后切换下拉框，你会发现页码重置了。
但是如果不点击查询是不会的。

这会导致一个bug，业务中删除后刷新页码不对等很多问题

**Comment by monkindey** [comment]
@ahooksjs/next-form-table@0.2.13-alpha.0

**Comment by monkindey** [comment]
@ahooksjs/next-form-table@0.2.13
