### ISSUE TITLE
期望支持配置-搜索时保留排序状态

### ISSUE THREAD

**Issue by caojinjie** [ahooksjs/useTable#4]
目前业务开发使用表格场景比较多，使用useNextFormTable比较方便也比较契合场景，不过我们需求定义要求执行手动搜索时，保留上一次的排序，而useNextFormTable内置重置了排序，使用方无法控制，期望可以支持配置允许保留排序。

**Comment by caojinjie** [comment]
使用官方demo即可查看搜索时重置排序的效果，https://usetable-ahooks.js.org/hooks/next/next-form-table#%E4%BB%A3%E7%A0%81%E6%BC%94%E7%A4%BA

**Comment by monkindey** [comment]
@ahooksjs/next-form-table@0.1.5 已经支持了
