### ISSUE TITLE
期望支持配置-数据刷新时，保留Selection勾选状态

### ISSUE THREAD

**Issue by caojinjie** [ahooksjs/useTable#5]
业务需求场景如下，表格中的列有状态一览，目前需求定义需要刷新状态，当前采用的实现方法是定间隔轮询表格数据，以达到状态刷新的效果，使用useNextFormTable的refreshDeps配置实现，不过该表格用户可以通过勾选做批量操作，useNextFormTable刷新时会自动去除勾选，需求期望轮询时能够保留勾选项。

**Comment by caojinjie** [comment]
使用官方demo集成`重新请求`和`useSelectionPlugin `即可查看现象，期望能够有一个让使用方可操作状态的入口作为扩展

**Comment by monkindey** [comment]
我点击【查询】或者【重置】的时候应该要清空勾选项吧。

**Comment by caojinjie** [comment]
手动刷新时是应该清空勾选项，不过目前的场景有存在自动轮询，期望轮询时不做清空，所以期望能够有个配置

**Comment by monkindey** [comment]
使用下 @ahooksjs/use-tree-plugin@0.1.6-alpha.0，使用插件如下

```js
  const selectionPlugin = useSelectionPlugin({
    primaryKey: 'phone',
    checkIsNeedReset: (ctx) => {
      if (ctx.meta.queryFrom === methods.ON_REFRESH_DEPS) {
        return false;
      }
      return true;
    },
  });
```
