### ISSUE TITLE
使用next-form-table查询表格，初始查询时可以指定排序吗？

### ISSUE THREAD

**Issue by caojinjie** [ahooksjs/useTable#7]
列表使用next-form-table实现，并且列表支持手动排序功能，如表格有名称、时间两列，默认按照时间排序，可以支持手动按照名称、时间排序，手动操作时可以正常响应事件，但是初试加载时如何能按照预定排序来执行呢？

**Comment by monkindey** [comment]
初始化的时候可以让后端处理默认排序吗？

**Comment by caojinjie** [comment]
可以让后端处理默认排序，不过目前场景下，页面的默认排序跟后端的默认排序不一样，后端的默认排序是按创建时间来排的，页面的默认排序是按名称来排的，而且后端表示，不期望将来页面默认排序的变化影响到后端编码，所以期望默认排序也由接口入参来控制

**Comment by caojinjie** [comment]
当前结合next-form-table使用时，我的使用方式如下，Table组件设置sort属性，
`          sort={
            Object.keys(tableProps.sort).length > 0
              ? tableProps.sort
              : { name: 'asc' }
          }`
然后在service中给sortBy、sortOrder默认值为name和asc

**Comment by caojinjie** [comment]
不知道next-form-table可不可以只设置一次默认的排序就可以达到效果，而不用在2个地方写默认排序

**Comment by monkindey** [comment]
v0.1.8 已解决
